In [1]:
#this file is where I tested most of the code on primarily the first Pokemon (Bulbasaur)

from bs4 import BeautifulSoup
import requests

In [2]:
pokemon = 'Bulbasaur'
pokemon2 = 'Mr-Mime'
pokemon3 = 'Rotom'

url = 'https://pokemondb.net/pokedex/' + pokemon

page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

#info taken (type) will only be based on the first (original) form given

forms_table = soup.find_all('div', class_ = 'sv-tabs-tab-list')[0]
print(forms_table)

<div class="sv-tabs-tab-list">
<a class="sv-tabs-tab active" href="#tab-basic-1">Bulbasaur</a>
</div>

In [3]:
forms = forms_table.find_all('a')
forms_count = len(forms)
forms_count

1

In [4]:
table = soup.find_all('div', class_ = 'grid-col span-md-12 span-lg-8')[forms_count]
print (table)

<div class="grid-col span-md-12 span-lg-8">
<h2>Where to find Bulbasaur</h2>
<div class="resp-scroll">
<table class="vitals-table">
<tbody>
<tr>
<th><span class="igame red">Red</span><br/><span class="igame blue">Blue</span></th>
<td><a href="/location/kanto-pallet-town">Pallet Town</a></td>
</tr>
<tr>
<th><span class="igame yellow">Yellow</span></th>
<td><a href="/location/kanto-cerulean-city">Cerulean City</a></td>
</tr>
<tr>
<th><span class="igame gold">Gold</span><br/><span class="igame silver">Silver</span><br/><span class="igame crystal">Crystal</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame ruby">Ruby</span><br/><span class="igame sapphire">Sapphire</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame firered">FireRed</span><br/><span class="igame leafgreen">LeafGreen</span></th>
<td><a href="/location/kanto-pallet-town">Pallet Town</a></td>
</tr>
<tr>
<th><span class="igame emerald">Emerald</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame diamond">Diamond</span><br/><span class="igame pearl">Pearl</span><br/><span class="igame platinum">Platinum</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame heartgold">HeartGold</span><br/><span class="igame soulsilver">SoulSilver</span></th>
<td><a href="/location/kanto-pallet-town">Pallet Town</a></td>
</tr>
<tr>
<th><span class="igame black">Black</span><br/><span class="igame white">White</span><br/><span class="igame black-2">Black 2</span><br/><span class="igame white-2">White 2</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame x">X</span><br/><span class="igame y">Y</span></th>
<td><a href="/location/kalos-lumiose-city">Lumiose City</a></td>
</tr>
<tr>
<th><span class="igame omega-ruby">Omega Ruby</span><br/><span class="igame alpha-sapphire">Alpha Sapphire</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame sun">Sun</span><br/><span class="igame moon">Moon</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame ultra-sun">Ultra Sun</span><br/><span class="igame ultra-moon">Ultra Moon</span></th>
<td><a href="/location/alola-route-2">Route 2</a></td>
</tr>
<tr>
<th><span class="igame lets-go-pikachu">Let's Go Pikachu</span><br/><span class="igame lets-go-eevee">Let's Go Eevee</span></th>
<td><a href="/location/kanto-cerulean-city">Cerulean City</a>, <a href="/location/kanto-viridian-forest">Viridian Forest</a></td>
</tr>
<tr>
<th><span class="igame sword">Sword</span><br/><span class="igame shield">Shield</span></th>
<td><small>Trade/migrate from another game</small></td>
</tr>
<tr>
<th><span class="igame brilliant-diamond">Brilliant Diamond</span><br/><span class="igame shining-pearl">Shining Pearl</span></th>
<td><a href="/location/sinnoh-grassland-cave">Grassland Cave</a>, <a href="/location/sinnoh-swampy-cave">Swampy Cave</a>, <a href="/location/sinnoh-riverbank-cave">Riverbank Cave</a>, <a href="/location/sinnoh-still-water-cavern">Still-Water Cavern</a>, <a href="/location/sinnoh-sunlit-cavern">Sunlit Cavern</a>, <a href="/location/sinnoh-bogsunk-cavern">Bogsunk Cavern</a></td>
</tr>
<tr>
<th><span class="igame legends-arceus">Legends: Arceus</span></th>
<td><small>Not available in this game</small></td>
</tr>
<tr>
<th><span class="igame scarlet">Scarlet</span><br/><span class="igame violet">Violet</span></th>
<td><small>Not available in this game</small></td>
</tr>
</tbody>
</table>
</div>
</div>

In [5]:
for br in table.find_all("br"):
    br.replace_with("\n")

games = table.find_all('th')
games

[<th><span class="igame red">Red</span>
 <span class="igame blue">Blue</span></th>,
 <th><span class="igame yellow">Yellow</span></th>,
 <th><span class="igame gold">Gold</span>
 <span class="igame silver">Silver</span>
 <span class="igame crystal">Crystal</span></th>,
 <th><span class="igame ruby">Ruby</span>
 <span class="igame sapphire">Sapphire</span></th>,
 <th><span class="igame firered">FireRed</span>
 <span class="igame leafgreen">LeafGreen</span></th>,
 <th><span class="igame emerald">Emerald</span></th>,
 <th><span class="igame diamond">Diamond</span>
 <span class="igame pearl">Pearl</span>
 <span class="igame platinum">Platinum</span></th>,
 <th><span class="igame heartgold">HeartGold</span>
 <span class="igame soulsilver">SoulSilver</span></th>,
 <th><span class="igame black">Black</span>
 <span class="igame white">White</span>
 <span class="igame black-2">Black 2</span>
 <span class="igame white-2">White 2</span></th>,
 <th><span class="igame x">X</span>
 <span class="igame y">Y</span></th>,
 <th><span class="igame omega-ruby">Omega Ruby</span>
 <span class="igame alpha-sapphire">Alpha Sapphire</span></th>,
 <th><span class="igame sun">Sun</span>
 <span class="igame moon">Moon</span></th>,
 <th><span class="igame ultra-sun">Ultra Sun</span>
 <span class="igame ultra-moon">Ultra Moon</span></th>,
 <th><span class="igame lets-go-pikachu">Let's Go Pikachu</span>
 <span class="igame lets-go-eevee">Let's Go Eevee</span></th>,
 <th><span class="igame sword">Sword</span>
 <span class="igame shield">Shield</span></th>,
 <th><span class="igame brilliant-diamond">Brilliant Diamond</span>
 <span class="igame shining-pearl">Shining Pearl</span></th>,
 <th><span class="igame legends-arceus">Legends: Arceus</span></th>,
 <th><span class="igame scarlet">Scarlet</span>
 <span class="igame violet">Violet</span></th>]

In [6]:

games2 = [title.text.splitlines() for title in games]
print(games2)

games3 = [item for sublist in games2 for item in sublist]
games3.insert(0,'Name')
headers = games3
print(games3)

[['Red', 'Blue'], ['Yellow'], ['Gold', 'Silver', 'Crystal'], ['Ruby', 'Sapphire'], ['FireRed', 'LeafGreen'], ['Emerald'], ['Diamond', 'Pearl', 'Platinum'], ['HeartGold', 'SoulSilver'], ['Black', 'White', 'Black 2', 'White 2'], ['X', 'Y'], ['Omega Ruby', 'Alpha Sapphire'], ['Sun', 'Moon'], ['Ultra Sun', 'Ultra Moon'], ["Let's Go Pikachu", "Let's Go Eevee"], ['Sword', 'Shield'], ['Brilliant Diamond', 'Shining Pearl'], ['Legends: Arceus'], ['Scarlet', 'Violet']]
['Name', 'Red', 'Blue', 'Yellow', 'Gold', 'Silver', 'Crystal', 'Ruby', 'Sapphire', 'FireRed', 'LeafGreen', 'Emerald', 'Diamond', 'Pearl', 'Platinum', 'HeartGold', 'SoulSilver', 'Black', 'White', 'Black 2', 'White 2', 'X', 'Y', 'Omega Ruby', 'Alpha Sapphire', 'Sun', 'Moon', 'Ultra Sun', 'Ultra Moon', "Let's Go Pikachu", "Let's Go Eevee", 'Sword', 'Shield', 'Brilliant Diamond', 'Shining Pearl', 'Legends: Arceus', 'Scarlet', 'Violet']

In [7]:
import pandas as pd
df = pd.DataFrame(columns = headers)

row_data = table.find_all('tr')
row_data

[<tr>
 <th><span class="igame red">Red</span>
 <span class="igame blue">Blue</span></th>
 <td><a href="/location/kanto-pallet-town">Pallet Town</a></td>
 </tr>,
 <tr>
 <th><span class="igame yellow">Yellow</span></th>
 <td><a href="/location/kanto-cerulean-city">Cerulean City</a></td>
 </tr>,
 <tr>
 <th><span class="igame gold">Gold</span>
 <span class="igame silver">Silver</span>
 <span class="igame crystal">Crystal</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame ruby">Ruby</span>
 <span class="igame sapphire">Sapphire</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame firered">FireRed</span>
 <span class="igame leafgreen">LeafGreen</span></th>
 <td><a href="/location/kanto-pallet-town">Pallet Town</a></td>
 </tr>,
 <tr>
 <th><span class="igame emerald">Emerald</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame diamond">Diamond</span>
 <span class="igame pearl">Pearl</span>
 <span class="igame platinum">Platinum</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame heartgold">HeartGold</span>
 <span class="igame soulsilver">SoulSilver</span></th>
 <td><a href="/location/kanto-pallet-town">Pallet Town</a></td>
 </tr>,
 <tr>
 <th><span class="igame black">Black</span>
 <span class="igame white">White</span>
 <span class="igame black-2">Black 2</span>
 <span class="igame white-2">White 2</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame x">X</span>
 <span class="igame y">Y</span></th>
 <td><a href="/location/kalos-lumiose-city">Lumiose City</a></td>
 </tr>,
 <tr>
 <th><span class="igame omega-ruby">Omega Ruby</span>
 <span class="igame alpha-sapphire">Alpha Sapphire</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame sun">Sun</span>
 <span class="igame moon">Moon</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame ultra-sun">Ultra Sun</span>
 <span class="igame ultra-moon">Ultra Moon</span></th>
 <td><a href="/location/alola-route-2">Route 2</a></td>
 </tr>,
 <tr>
 <th><span class="igame lets-go-pikachu">Let's Go Pikachu</span>
 <span class="igame lets-go-eevee">Let's Go Eevee</span></th>
 <td><a href="/location/kanto-cerulean-city">Cerulean City</a>, <a href="/location/kanto-viridian-forest">Viridian Forest</a></td>
 </tr>,
 <tr>
 <th><span class="igame sword">Sword</span>
 <span class="igame shield">Shield</span></th>
 <td><small>Trade/migrate from another game</small></td>
 </tr>,
 <tr>
 <th><span class="igame brilliant-diamond">Brilliant Diamond</span>
 <span class="igame shining-pearl">Shining Pearl</span></th>
 <td><a href="/location/sinnoh-grassland-cave">Grassland Cave</a>, <a href="/location/sinnoh-swampy-cave">Swampy Cave</a>, <a href="/location/sinnoh-riverbank-cave">Riverbank Cave</a>, <a href="/location/sinnoh-still-water-cavern">Still-Water Cavern</a>, <a href="/location/sinnoh-sunlit-cavern">Sunlit Cavern</a>, <a href="/location/sinnoh-bogsunk-cavern">Bogsunk Cavern</a></td>
 </tr>,
 <tr>
 <th><span class="igame legends-arceus">Legends: Arceus</span></th>
 <td><small>Not available in this game</small></td>
 </tr>,
 <tr>
 <th><span class="igame scarlet">Scarlet</span>
 <span class="igame violet">Violet</span></th>
 <td><small>Not available in this game</small></td>
 </tr>]

In [16]:
values = [None] * 38
dictionary = dict(zip(games3, values))

test = [title.text.strip() for title in row_data]

print(test)


test2 = []
i = 0
for x in test:
    newlines = len(x.splitlines()) - 1

    for y in range(newlines):
        pair = {x.splitlines()[y]:x.splitlines()[newlines]}
        test2.append(pair)
        i += 1

print(test2)

for x in test2:
    dictionary.update(x)
    
pair = {'Name':pokemon}
dictionary.update(pair)
print(dictionary)

['Red\nBlue\nPallet Town', 'Yellow\nCerulean City', 'Gold\nSilver\nCrystal\nTrade/migrate from another game', 'Ruby\nSapphire\nTrade/migrate from another game', 'FireRed\nLeafGreen\nPallet Town', 'Emerald\nTrade/migrate from another game', 'Diamond\nPearl\nPlatinum\nTrade/migrate from another game', 'HeartGold\nSoulSilver\nPallet Town', 'Black\nWhite\nBlack 2\nWhite 2\nTrade/migrate from another game', 'X\nY\nLumiose City', 'Omega Ruby\nAlpha Sapphire\nTrade/migrate from another game', 'Sun\nMoon\nTrade/migrate from another game', 'Ultra Sun\nUltra Moon\nRoute 2', "Let's Go Pikachu\nLet's Go Eevee\nCerulean City, Viridian Forest", 'Sword\nShield\nTrade/migrate from another game', 'Brilliant Diamond\nShining Pearl\nGrassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern', 'Legends: Arceus\nNot available in this game', 'Scarlet\nViolet\nNot available in this game']
[{'Red': 'Pallet Town'}, {'Blue': 'Pallet Town'}, {'Yellow': 'Cerulean City'}, {'Gold': 'Trade/migrate from another game'}, {'Silver': 'Trade/migrate from another game'}, {'Crystal': 'Trade/migrate from another game'}, {'Ruby': 'Trade/migrate from another game'}, {'Sapphire': 'Trade/migrate from another game'}, {'FireRed': 'Pallet Town'}, {'LeafGreen': 'Pallet Town'}, {'Emerald': 'Trade/migrate from another game'}, {'Diamond': 'Trade/migrate from another game'}, {'Pearl': 'Trade/migrate from another game'}, {'Platinum': 'Trade/migrate from another game'}, {'HeartGold': 'Pallet Town'}, {'SoulSilver': 'Pallet Town'}, {'Black': 'Trade/migrate from another game'}, {'White': 'Trade/migrate from another game'}, {'Black 2': 'Trade/migrate from another game'}, {'White 2': 'Trade/migrate from another game'}, {'X': 'Lumiose City'}, {'Y': 'Lumiose City'}, {'Omega Ruby': 'Trade/migrate from another game'}, {'Alpha Sapphire': 'Trade/migrate from another game'}, {'Sun': 'Trade/migrate from another game'}, {'Moon': 'Trade/migrate from another game'}, {'Ultra Sun': 'Route 2'}, {'Ultra Moon': 'Route 2'}, {"Let's Go Pikachu": 'Cerulean City, Viridian Forest'}, {"Let's Go Eevee": 'Cerulean City, Viridian Forest'}, {'Sword': 'Trade/migrate from another game'}, {'Shield': 'Trade/migrate from another game'}, {'Brilliant Diamond': 'Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern'}, {'Shining Pearl': 'Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern'}, {'Legends: Arceus': 'Not available in this game'}, {'Scarlet': 'Not available in this game'}, {'Violet': 'Not available in this game'}]
{'Red': 'Pallet Town', 'Blue': 'Pallet Town', 'Yellow': 'Cerulean City', 'Gold': 'Trade/migrate from another game', 'Silver': 'Trade/migrate from another game', 'Crystal': 'Trade/migrate from another game', 'Ruby': 'Trade/migrate from another game', 'Sapphire': 'Trade/migrate from another game', 'FireRed': 'Pallet Town', 'LeafGreen': 'Pallet Town', 'Emerald': 'Trade/migrate from another game', 'Diamond': 'Trade/migrate from another game', 'Pearl': 'Trade/migrate from another game', 'Platinum': 'Trade/migrate from another game', 'HeartGold': 'Pallet Town', 'SoulSilver': 'Pallet Town', 'Black': 'Trade/migrate from another game', 'White': 'Trade/migrate from another game', 'Black 2': 'Trade/migrate from another game', 'White 2': 'Trade/migrate from another game', 'X': 'Lumiose City', 'Y': 'Lumiose City', 'Omega Ruby': 'Trade/migrate from another game', 'Alpha Sapphire': 'Trade/migrate from another game', 'Sun': 'Trade/migrate from another game', 'Moon': 'Trade/migrate from another game', 'Ultra Sun': 'Route 2', 'Ultra Moon': 'Route 2', "Let's Go Pikachu": 'Cerulean City, Viridian Forest', "Let's Go Eevee": 'Cerulean City, Viridian Forest', 'Sword': 'Trade/migrate from another game', 'Shield': 'Trade/migrate from another game', 'Brilliant Diamond': 'Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern', 'Shining Pearl': 'Grassland Cave, Swampy Cave, Riverbank Cave, Still-Water Cavern, Sunlit Cavern, Bogsunk Cavern', 'Legends: Arceus': 'Not available in this game', 'Scarlet': 'Not available in this game', 'Violet': 'Not available in this game', 'Name': 'Bulbasaur'}

In [9]:
table2 = soup.find_all('table', class_ = 'vitals-table')[0]
table2

type1 = table2.find_all('a')[0].text
type2 = table2.find_all('a')[1].text
print(type1)
print(type2)

types_list = ['Normal','Fire','Water','Electric','Grass','Ice','Fighting','Poison','Ground','Flying','Psychic','Bug','Rock','Ghost','Dragon','Dark','Steel','Fairy']

if type2 not in types_list:
    type2 = 'None'

pair1 = {'Type1': type1}
pair2 = {'Type2': type2}
dictionary.update(pair1)
dictionary.update(pair2)

Grass
Poison

In [10]:
test_df = pd.DataFrame([dictionary])

df = pd.concat([df, test_df], ignore_index=True)
names = df.pop("Name")
df.insert(0,"Name", names)
type1s = df.pop("Type1")
df.insert(1,"Type1", type1s)
type2s = df.pop("Type2")
df.insert(2,"Type2", type2s)

df

,Name,Type1,Type2,Red,Blue,Yellow,Gold,Silver,Crystal,Ruby,...,Ultra Moon,Let's Go Pikachu,Let's Go Eevee,Sword,Shield,Brilliant Diamond,Shining Pearl,Legends: Arceus,Scarlet,Violet
0,Bulbasaur,Grass,Poison,Pallet Town,Pallet Town,Cerulean City,Trade/migrate from another game,Trade/migrate from another game,Trade/migrate from another game,Trade/migrate from another game,...,Route 2,"Cerulean City, Viridian Forest","Cerulean City, Viridian Forest",Trade/migrate from another game,Trade/migrate from another game,"Grassland Cave, Swampy Cave, Riverbank Cave, S...","Grassland Cave, Swampy Cave, Riverbank Cave, S...",Not available in this game,Not available in this game,Not available in this game

In [11]:
df = pd.read_csv('data.csv')

#replace "Trade/migrate from another game", "Not available in this game", and Na values with 0

df.replace('Trade/migrate from another game', 0, inplace=True)
df.replace('Not available in this game', 0, inplace=True)
df.fillna(0, inplace=True)

#replace all non-zero values in columns except first three with 1s 

games3.remove("Name")

for game in games3:
    df[game] = df[game].where(df[game] == 0, 1)

df.to_csv(r'C:\Users\jonat\Documents\to website\web scraping project (pokemon)\finaldata.csv', index = False)
df

,Name,Type1,Type2,Red,Blue,Yellow,Gold,Silver,Crystal,Ruby,...,Ultra Moon,Let's Go Pikachu,Let's Go Eevee,Sword,Shield,Brilliant Diamond,Shining Pearl,Legends: Arceus,Scarlet,Violet
0,Bulbasaur,Grass,Poison,1,1,1,0,0,0,0,...,1,1,1,0,0,1,1,0,0,0
1,Ivysaur,Grass,Poison,1,1,1,0,0,0,0,...,1,1,1,0,0,1,1,0,0,0
2,Venusaur,Grass,Poison,1,1,1,0,0,0,0,...,1,1,1,0,0,1,1,0,0,0
3,Charmander,Fire,None,1,1,1,0,0,0,0,...,1,1,1,0,0,1,1,0,0,0
4,Charmeleon,Fire,None,1,1,1,0,0,0,0,...,1,1,1,0,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,Iron-Valiant,Fairy,Fighting,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1006,Koraidon,Fighting,Dragon,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1007,Miraidon,Electric,Dragon,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1008,Walking-Wake,Water,Dragon,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1009,Iron-Leaves,Grass,Psychic,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
#create second dataframe to hold type totals

if "Type" not in games3:
    games3.insert(0,'Type')

print(games3)
new_df = pd.DataFrame(columns = games3)
if "Type" in games3:
    games3.remove('Type')

if "None" not in types_list:
    types_list.append('None')

for type in types_list:
    #go through original df, if type is in type1 or type2, add data
    new_row = []
    new_row.append(type)
    for game in games3:
        total = 0
        for index, row in df.iterrows():
            if row['Type1'] == type or row['Type2'] == type:
                total += row[game]     
        new_row.append(total)
    print(new_row)
    length = len(new_df)
    new_df.loc[length] = new_row

#want a total row at the end where it shows the total number of pokemon available in each game

total_row = []
total_row.append ("Total")
for game in games3:
    total = 0
    for index, row in df.iterrows():
        total += row[game]
    total_row.append(total)

length = len(new_df)
new_df.loc[length] = total_row
print(total_row)

new_df.to_csv(r'C:\Users\jonat\Documents\to website\web scraping project (pokemon)\type_total_by_game.csv', index = False)
new_df

['Type', 'Red', 'Blue', 'Yellow', 'Gold', 'Silver', 'Crystal', 'Ruby', 'Sapphire', 'FireRed', 'LeafGreen', 'Emerald', 'Diamond', 'Pearl', 'Platinum', 'HeartGold', 'SoulSilver', 'Black', 'White', 'Black 2', 'White 2', 'X', 'Y', 'Omega Ruby', 'Alpha Sapphire', 'Sun', 'Moon', 'Ultra Sun', 'Ultra Moon', "Let's Go Pikachu", "Let's Go Eevee", 'Sword', 'Shield', 'Brilliant Diamond', 'Shining Pearl', 'Legends: Arceus', 'Scarlet', 'Violet']
['Normal', 20, 22, 20, 35, 35, 36, 24, 23, 29, 29, 34, 69, 71, 70, 59, 63, 43, 64, 40, 42, 59, 59, 62, 61, 48, 48, 65, 66, 21, 22, 55, 54, 54, 57, 32, 54, 53]
['Fire', 9, 10, 11, 16, 16, 16, 10, 10, 13, 15, 16, 19, 21, 22, 26, 26, 21, 21, 22, 22, 23, 21, 33, 32, 27, 24, 46, 38, 10, 11, 24, 23, 23, 26, 17, 27, 28]
['Water', 32, 32, 32, 43, 42, 41, 42, 46, 36, 37, 52, 72, 77, 76, 67, 64, 76, 86, 77, 77, 78, 77, 82, 87, 71, 71, 107, 108, 32, 32, 82, 85, 74, 78, 35, 48, 50]
['Electric', 9, 8, 8, 16, 16, 13, 13, 13, 12, 10, 16, 26, 26, 27, 24, 24, 13, 27, 20, 22, 24, 26, 28, 28, 24, 24, 33, 36, 9, 9, 34, 34, 22, 19, 18, 32, 34]
['Grass', 11, 11, 14, 20, 20, 21, 18, 18, 15, 14, 25, 42, 42, 45, 42, 42, 33, 52, 35, 35, 43, 43, 51, 51, 37, 36, 49, 48, 11, 11, 47, 47, 41, 41, 23, 41, 40]
['Ice', 5, 5, 4, 8, 9, 9, 6, 6, 9, 8, 6, 17, 19, 22, 12, 13, 21, 21, 21, 21, 23, 24, 14, 14, 19, 19, 29, 29, 5, 5, 32, 33, 19, 18, 16, 18, 20]
['Fighting', 8, 6, 8, 11, 9, 9, 11, 11, 11, 11, 9, 23, 23, 23, 19, 17, 27, 30, 20, 19, 25, 26, 31, 31, 25, 24, 37, 36, 8, 6, 31, 28, 21, 21, 12, 26, 26]
['Poison', 30, 28, 26, 34, 32, 34, 16, 17, 34, 31, 18, 47, 45, 45, 41, 41, 21, 37, 23, 23, 50, 52, 31, 30, 28, 28, 31, 33, 26, 28, 40, 44, 44, 44, 21, 32, 31]
['Ground', 12, 14, 14, 22, 23, 24, 22, 21, 21, 21, 25, 44, 42, 41, 36, 31, 33, 43, 28, 30, 42, 44, 39, 38, 30, 32, 46, 47, 14, 12, 47, 52, 44, 42, 24, 34, 31]
['Flying', 19, 18, 19, 30, 32, 34, 21, 21, 34, 31, 27, 55, 53, 58, 53, 53, 50, 63, 38, 38, 70, 71, 39, 39, 42, 43, 68, 70, 19, 18, 49, 47, 51, 46, 33, 40, 40]
['Psychic', 13, 13, 12, 21, 21, 21, 25, 25, 18, 22, 26, 42, 45, 45, 43, 41, 32, 39, 32, 30, 43, 42, 45, 46, 27, 28, 47, 51, 13, 13, 51, 52, 34, 37, 19, 34, 32]
['Bug', 11, 11, 9, 20, 20, 22, 16, 16, 18, 17, 21, 44, 43, 45, 40, 40, 40, 49, 26, 26, 44, 44, 39, 39, 30, 30, 45, 45, 11, 11, 43, 43, 33, 32, 21, 28, 27]
['Rock', 11, 11, 11, 14, 14, 14, 18, 18, 15, 15, 19, 36, 30, 37, 28, 28, 35, 41, 38, 38, 49, 49, 46, 46, 29, 29, 55, 56, 11, 11, 41, 44, 20, 19, 16, 19, 16]
['Ghost', 3, 3, 3, 4, 4, 4, 5, 6, 3, 4, 6, 16, 18, 16, 8, 7, 15, 20, 14, 14, 22, 22, 16, 17, 22, 23, 31, 29, 3, 3, 37, 39, 10, 13, 15, 26, 28]
['Dragon', 3, 3, 3, 4, 4, 4, 10, 10, 4, 4, 10, 12, 15, 14, 11, 11, 14, 19, 17, 17, 28, 29, 23, 22, 27, 27, 37, 38, 3, 3, 32, 30, 10, 13, 9, 26, 27]
['Dark', 0, 0, 0, 6, 6, 6, 9, 8, 3, 3, 12, 21, 16, 19, 14, 13, 27, 26, 25, 23, 33, 33, 24, 23, 18, 20, 31, 32, 0, 0, 36, 33, 19, 13, 12, 38, 31]
['Steel', 2, 2, 2, 5, 6, 6, 11, 10, 5, 3, 12, 23, 18, 24, 14, 16, 22, 28, 30, 30, 24, 21, 27, 26, 22, 21, 32, 30, 2, 2, 36, 35, 18, 16, 14, 23, 24]
['Fairy', 5, 5, 5, 13, 13, 13, 10, 9, 12, 12, 12, 20, 20, 20, 16, 17, 9, 18, 11, 11, 24, 23, 17, 16, 30, 28, 35, 32, 5, 5, 37, 36, 17, 16, 13, 27, 26]
['None', 75, 76, 75, 122, 122, 119, 99, 98, 100, 101, 130, 216, 220, 221, 193, 195, 168, 216, 179, 178, 204, 202, 249, 250, 190, 191, 242, 242, 75, 76, 238, 233, 190, 197, 130, 185, 194]
['Total', 139, 139, 138, 222, 222, 223, 193, 193, 196, 194, 238, 422, 422, 435, 373, 371, 350, 450, 348, 348, 454, 454, 448, 448, 373, 373, 533, 533, 139, 139, 496, 496, 372, 374, 240, 379, 379]

,Type,Red,Blue,Yellow,Gold,Silver,Crystal,Ruby,Sapphire,FireRed,...,Ultra Moon,Let's Go Pikachu,Let's Go Eevee,Sword,Shield,Brilliant Diamond,Shining Pearl,Legends: Arceus,Scarlet,Violet
0,Normal,20,22,20,35,35,36,24,23,29,...,66,21,22,55,54,54,57,32,54,53
1,Fire,9,10,11,16,16,16,10,10,13,...,38,10,11,24,23,23,26,17,27,28
2,Water,32,32,32,43,42,41,42,46,36,...,108,32,32,82,85,74,78,35,48,50
3,Electric,9,8,8,16,16,13,13,13,12,...,36,9,9,34,34,22,19,18,32,34
4,Grass,11,11,14,20,20,21,18,18,15,...,48,11,11,47,47,41,41,23,41,40
5,Ice,5,5,4,8,9,9,6,6,9,...,29,5,5,32,33,19,18,16,18,20
6,Fighting,8,6,8,11,9,9,11,11,11,...,36,8,6,31,28,21,21,12,26,26
7,Poison,30,28,26,34,32,34,16,17,34,...,33,26,28,40,44,44,44,21,32,31
8,Ground,12,14,14,22,23,24,22,21,21,...,47,14,12,47,52,44,42,24,34,31
9,Flying,19,18,19,30,32,34,21,21,34,...,70,19,18,49,47,51,46,33,40,40
10,Psychic,13,13,12,21,21,21,25,25,18,...,51,13,13,51,52,34,37,19,34,32
11,Bug,11,11,9,20,20,22,16,16,18,...,45,11,11,43,43,33,32,21,28,27
12,Rock,11,11,11,14,14,14,18,18,15,...,56,11,11,41,44,20,19,16,19,16
13,Ghost,3,3,3,4,4,4,5,6,3,...,29,3,3,37,39,10,13,15,26,28
14,Dragon,3,3,3,4,4,4,10,10,4,...,38,3,3,32,30,10,13,9,26,27
15,Dark,0,0,0,6,6,6,9,8,3,...,32,0,0,36,33,19,13,12,38,31
16,Steel,2,2,2,5,6,6,11,10,5,...,30,2,2,36,35,18,16,14,23,24
17,Fairy,5,5,5,13,13,13,10,9,12,...,32,5,5,37,36,17,16,13,27,26
18,None,75,76,75,122,122,119,99,98,100,...,242,75,76,238,233,190,197,130,185,194
19,Total,139,139,138,222,222,223,193,193,196,...,533,139,139,496,496,372,374,240,379,379

In [13]:
new_df['Total'] = ([0] * 20)

for game in games3:
   new_df['Total'] = new_df['Total'] + new_df[game]

new_df.to_csv(r'C:\Users\jonat\Documents\to website\web scraping project (pokemon)\type_total_by_game.csv', index = False)
new_df

,Type,Red,Blue,Yellow,Gold,Silver,Crystal,Ruby,Sapphire,FireRed,...,Let's Go Pikachu,Let's Go Eevee,Sword,Shield,Brilliant Diamond,Shining Pearl,Legends: Arceus,Scarlet,Violet,Total
0,Normal,20,22,20,35,35,36,24,23,29,...,21,22,55,54,54,57,32,54,53,1698
1,Fire,9,10,11,16,16,16,10,10,13,...,10,11,24,23,23,26,17,27,28,775
2,Water,32,32,32,43,42,41,42,46,36,...,32,32,82,85,74,78,35,48,50,2304
3,Electric,9,8,8,16,16,13,13,13,12,...,9,9,34,34,22,19,18,32,34,777
4,Grass,11,11,14,20,20,21,18,18,15,...,11,11,47,47,41,41,23,41,40,1215
5,Ice,5,5,4,8,9,9,6,6,9,...,5,5,32,33,19,18,16,18,20,579
6,Fighting,8,6,8,11,9,9,11,11,11,...,8,6,31,28,21,21,12,26,26,719
7,Poison,30,28,26,34,32,34,16,17,34,...,26,28,40,44,44,44,21,32,31,1216
8,Ground,12,14,14,22,23,24,22,21,21,...,14,12,47,52,44,42,24,34,31,1165
9,Flying,19,18,19,30,32,34,21,21,34,...,19,18,49,47,51,46,33,40,40,1532
10,Psychic,13,13,12,21,21,21,25,25,18,...,13,13,51,52,34,37,19,34,32,1180
11,Bug,11,11,9,20,20,22,16,16,18,...,11,11,43,43,33,32,21,28,27,1099
12,Rock,11,11,11,14,14,14,18,18,15,...,11,11,41,44,20,19,16,19,16,1027
13,Ghost,3,3,3,4,4,4,5,6,3,...,3,3,37,39,10,13,15,26,28,529
14,Dragon,3,3,3,4,4,4,10,10,4,...,3,3,32,30,10,13,9,26,27,573
15,Dark,0,0,0,6,6,6,9,8,3,...,0,0,36,33,19,13,12,38,31,633
16,Steel,2,2,2,5,6,6,11,10,5,...,2,2,36,35,18,16,14,23,24,642
17,Fairy,5,5,5,13,13,13,10,9,12,...,5,5,37,36,17,16,13,27,26,638
18,None,75,76,75,122,122,119,99,98,100,...,75,76,238,233,190,197,130,185,194,6191
19,Total,139,139,138,222,222,223,193,193,196,...,139,139,496,496,372,374,240,379,379,12246

In [14]:
#want data with percentages

new_df = pd.read_csv('type_total_by_game.csv')

#save total row to add later
totals = new_df.iloc[19]

i=1
for column in new_df:
    if column != 'Type':
        new_df[column] = new_df[column] / new_df.iloc[19][i]
        i += 1

new_df.loc[19] = totals

new_df.to_csv(r'C:\Users\jonat\Documents\to website\web scraping project (pokemon)\type_percentages_by_game.csv', index = False)
new_df

,Type,Red,Blue,Yellow,Gold,Silver,Crystal,Ruby,Sapphire,FireRed,...,Let's Go Pikachu,Let's Go Eevee,Sword,Shield,Brilliant Diamond,Shining Pearl,Legends: Arceus,Scarlet,Violet,Total
0,Normal,0.143885,0.158273,0.144928,0.157658,0.157658,0.161435,0.124352,0.119171,0.147959,...,0.151079,0.158273,0.110887,0.108871,0.145161,0.152406,0.133333,0.142480,0.139842,0.138658
1,Fire,0.064748,0.071942,0.079710,0.072072,0.072072,0.071749,0.051813,0.051813,0.066327,...,0.071942,0.079137,0.048387,0.046371,0.061828,0.069519,0.070833,0.071240,0.073879,0.063286
2,Water,0.230216,0.230216,0.231884,0.193694,0.189189,0.183857,0.217617,0.238342,0.183673,...,0.230216,0.230216,0.165323,0.171371,0.198925,0.208556,0.145833,0.126649,0.131926,0.188143
3,Electric,0.064748,0.057554,0.057971,0.072072,0.072072,0.058296,0.067358,0.067358,0.061224,...,0.064748,0.064748,0.068548,0.068548,0.059140,0.050802,0.075000,0.084433,0.089710,0.063449
4,Grass,0.079137,0.079137,0.101449,0.090090,0.090090,0.094170,0.093264,0.093264,0.076531,...,0.079137,0.079137,0.094758,0.094758,0.110215,0.109626,0.095833,0.108179,0.105541,0.099216
5,Ice,0.035971,0.035971,0.028986,0.036036,0.040541,0.040359,0.031088,0.031088,0.045918,...,0.035971,0.035971,0.064516,0.066532,0.051075,0.048128,0.066667,0.047493,0.052770,0.047281
6,Fighting,0.057554,0.043165,0.057971,0.049550,0.040541,0.040359,0.056995,0.056995,0.056122,...,0.057554,0.043165,0.062500,0.056452,0.056452,0.056150,0.050000,0.068602,0.068602,0.058713
7,Poison,0.215827,0.201439,0.188406,0.153153,0.144144,0.152466,0.082902,0.088083,0.173469,...,0.187050,0.201439,0.080645,0.088710,0.118280,0.117647,0.087500,0.084433,0.081794,0.099298
8,Ground,0.086331,0.100719,0.101449,0.099099,0.103604,0.107623,0.113990,0.108808,0.107143,...,0.100719,0.086331,0.094758,0.104839,0.118280,0.112299,0.100000,0.089710,0.081794,0.095133
9,Flying,0.136691,0.129496,0.137681,0.135135,0.144144,0.152466,0.108808,0.108808,0.173469,...,0.136691,0.129496,0.098790,0.094758,0.137097,0.122995,0.137500,0.105541,0.105541,0.125102
10,Psychic,0.093525,0.093525,0.086957,0.094595,0.094595,0.094170,0.129534,0.129534,0.091837,...,0.093525,0.093525,0.102823,0.104839,0.091398,0.098930,0.079167,0.089710,0.084433,0.096358
11,Bug,0.079137,0.079137,0.065217,0.090090,0.090090,0.098655,0.082902,0.082902,0.091837,...,0.079137,0.079137,0.086694,0.086694,0.088710,0.085561,0.087500,0.073879,0.071240,0.089744
12,Rock,0.079137,0.079137,0.079710,0.063063,0.063063,0.062780,0.093264,0.093264,0.076531,...,0.079137,0.079137,0.082661,0.088710,0.053763,0.050802,0.066667,0.050132,0.042216,0.083864
13,Ghost,0.021583,0.021583,0.021739,0.018018,0.018018,0.017937,0.025907,0.031088,0.015306,...,0.021583,0.021583,0.074597,0.078629,0.026882,0.034759,0.062500,0.068602,0.073879,0.043198
14,Dragon,0.021583,0.021583,0.021739,0.018018,0.018018,0.017937,0.051813,0.051813,0.020408,...,0.021583,0.021583,0.064516,0.060484,0.026882,0.034759,0.037500,0.068602,0.071240,0.046791
15,Dark,0.000000,0.000000,0.000000,0.027027,0.027027,0.026906,0.046632,0.041451,0.015306,...,0.000000,0.000000,0.072581,0.066532,0.051075,0.034759,0.050000,0.100264,0.081794,0.051690
16,Steel,0.014388,0.014388,0.014493,0.022523,0.027027,0.026906,0.056995,0.051813,0.025510,...,0.014388,0.014388,0.072581,0.070565,0.048387,0.042781,0.058333,0.060686,0.063325,0.052425
17,Fairy,0.035971,0.035971,0.036232,0.058559,0.058559,0.058296,0.051813,0.046632,0.061224,...,0.035971,0.035971,0.074597,0.072581,0.045699,0.042781,0.054167,0.071240,0.068602,0.052099
18,None,0.539568,0.546763,0.543478,0.549550,0.549550,0.533632,0.512953,0.507772,0.510204,...,0.539568,0.546763,0.479839,0.469758,0.510753,0.526738,0.541667,0.488127,0.511873,0.505553
19,Total,139.000000,139.000000,138.000000,222.000000,222.000000,223.000000,193.000000,193.000000,196.000000,...,139.000000,139.000000,496.000000,496.000000,372.000000,374.000000,240.000000,379.000000,379.000000,12246.000000